### ISSUE TITLE
/show/full/:result_id doesn't return using node 4.2.2

### ISSUE THREAD

**Issue by tarekrached** [tagomoris/shib#48]
Hi, thanks for making an awesome query tool!

I wasn't able to get the `/show/full/:result_id` route to work under node 4.2.2 - it basically pauses after sending the chunk [on L542 of app.js](https://github.com/tagomoris/shib/blob/master/app.js#L542).  It doesn't look like the `drain` event is being emitted from the res, which would normally trigger the `resume` on [L549](https://github.com/tagomoris/shib/blob/master/app.js#L549).

I was able to get it working by adding another `rStream.resume();` after the `res.write(chunk);` on [L542](https://github.com/tagomoris/shib/blob/master/app.js#L542), but this seems kludgy.

Out of curiosity, it seems like this route is just sending the result file from the filesystem, why not use [res.sendfile](http://expressjs.com/en/3x/api.html#res.sendfile)?

**Comment by tarekrached** [comment]
Same issue with `/download/tsv/:resultid` at [L610](https://github.com/tagomoris/shib/blob/master/app.js#L610)

**Comment by tarekrached** [comment]
I should say, I'm happy to make a pull request, although I think res.sendfile seems like a cleaner solution.

**Comment by tarekrached** [comment]
created [PR 49](https://github.com/tagomoris/shib/pull/49) - feel free to ignore if you'd rather a different approach!

**Comment by wyukawa** [comment]
merged https://github.com/tagomoris/shib/pull/49
So, I close this issue.
