### ISSUE TITLE
npm start fails with "NODE_PATH=lib node app.js"

### ISSUE THREAD

**Issue by apoku** [tagomoris/shib#56]
Just tried to setup shib on a windows machine...didn't get past npm start--hoping someone can shed some light on what this error is?

[npm-debug.txt](https://github.com/tagomoris/shib/files/196501/npm-debug.txt)

C:\Users\sandbox\NodeHDFS\shib>npm start

> shib@1.0.0 start C:\Users\sandbox\NodeHDFS\shib
> NODE_PATH=lib node app.js

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! shib@1.0.0 start: `NODE_PATH=lib node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shib@1.0.0 start script 'NODE_PATH=lib node app.js'.
npm ERR! This is most likely a problem with the shib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=lib node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls shib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sandbox\NodeHDFS\shib\npm-debug.log

C:\Users\sandbox\NodeHDFS\shib>node --version
v4.2.3

**Comment by apoku** [comment]
Ok...think I got it sorted out. I needed to tweak setting the NODE_ENV and NODE_PATH for Windows and specifically  [(the instructions were examples for a Linux environment...)](http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows)

`
SET NODE_ENV=config
`
The shib app is now running and my console outputs:
`
C:\Users\sandbox\NodeHDFS\shib>node app.js
(node) util.puts is deprecated. Use console.log instead.
3/30/2016, 6:18:56 PM [INFO] : Starting shib.
`

**Comment by tagomoris** [comment]
OK, it's good to hear that it works well on your environment.

**Comment by akashkool** [comment]
```
shib@1.0.0 start E:\Project\Presto-UI\shib-master
 NODE_PATH=lib node app.js

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shib@1.0.0 start: `NODE_PATH=lib node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shib@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akashk\AppData\Roaming\npm-cache\_logs\2018-08-01T09_22_07_661Z-debug.log

]([url](url))]([url]([url]([url](url))))
```

same issue. Please help.

**Comment by mtejagithub** [comment]
Hi , I have the same issue . Where exactly to set the   SET NODE_ENV=config   . Can you please help on this .
